### ISSUE TITLE
Build instructions for the Haskell-impaired

### ISSUE THREAD

**Issue by nkurz** [RaphaelJ/fast_strstr#2]
It would help if the Readme offered some very simple build instructions for those unfamiliar with Haskell.  This is not necessary, of course, but might help you get exposure to a wider audience.  I stumbled through with the help of Google, but it was awkward.

**Comment by RaphaelJ** [comment]
Fixed in b17f4b0e883d934e66104f6d792706f8492ffd94.

Sorry for the inconvenience.
