### ISSUE TITLE
could you compare my mie::strstr()?

### ISSUE THREAD

**Issue by herumi** [RaphaelJ/fast_strstr#5]
I add my mie::strstr() to compare strstr()/fast_strstr().
https://github.com/herumi/fast_strstr/commit/6c69fbe65874eea73bd4e2389fc5f4e472a0660a

This benchmark requires https://github.com/herumi/xbyak .
In my environment(Core i7-4770, gcc 4.8.2, Ubuntu 14.04, EGLIBC 2.19), mie::strstr() seems to be faster than strstr()/fast_strstr() for small size.
Of cource, the timings is depend on texts. Could you test the benchmark?

warming up
estimating clock resolution...
mean is 781.6979 ns (640001 iterations)
found 1033621 outliers among 639999 samples (161.5%)
  542498 (84.8%) low severe
  491123 (76.7%) high severe
estimating cost of a clock call...
mean is 27.71601 ns (5 iterations)

benchmarking 10/strstr()
mean: 1.133995 us, lb 1.133489 us, ub 1.134767 us, ci 0.950
std dev: 3.166250 ns, lb 2.332570 ns, ub 5.084766 ns, ci 0.950

benchmarking 10/fast_strstr()
mean: 1.153613 us, lb 1.153208 us, ub 1.154120 us, ci 0.950
std dev: 2.319005 ns, lb 1.921740 ns, ub 2.804740 ns, ci 0.950

benchmarking 10/mie_strstr()
mean: 898.6803 ns, lb 898.3080 ns, ub 899.1812 ns, ci 0.950
std dev: 2.193393 ns, lb 1.751410 ns, ub 3.016018 ns, ci 0.950

benchmarking 100/strstr()
mean: 1.894278 us, lb 1.893524 us, ub 1.895188 us, ci 0.950
std dev: 4.215399 ns, lb 3.543868 ns, ub 4.999982 ns, ci 0.950

benchmarking 100/fast_strstr()
mean: 2.043720 us, lb 2.041463 us, ub 2.047509 us, ci 0.950
std dev: 14.69081 ns, lb 9.752714 ns, ub 20.61726 ns, ci 0.950

benchmarking 100/mie_strstr()
mean: 1.218722 us, lb 1.217167 us, ub 1.221374 us, ci 0.950
std dev: 10.20777 ns, lb 6.859882 ns, ub 15.52274 ns, ci 0.950

benchmarking 500/strstr()
mean: 3.811585 us, lb 3.809526 us, ub 3.814097 us, ci 0.950
std dev: 11.63290 ns, lb 9.687406 ns, ub 14.53447 ns, ci 0.950

benchmarking 500/fast_strstr()
mean: 15.73307 us, lb 15.72577 us, ub 15.74771 us, ci 0.950
std dev: 51.13517 ns, lb 31.01187 ns, ub 99.52022 ns, ci 0.950

benchmarking 500/mie_strstr()
mean: 3.971047 us, lb 3.967470 us, ub 3.977127 us, ci 0.950
std dev: 23.51025 ns, lb 15.29978 ns, ub 37.20215 ns, ci 0.950

benchmarking 1000/strstr()
mean: 6.855369 us, lb 6.693461 us, ub 7.069631 us, ci 0.950
std dev: 960.6820 ns, lb 767.0566 ns, ub 1.132076 us, ci 0.950
found 15 outliers among 100 samples (15.0%)
  15 (15.0%) high severe
variance introduced by outliers: 88.370%
variance is severely inflated by outliers

benchmarking 1000/fast_strstr()
mean: 39.53926 us, lb 39.47262 us, ub 39.77256 us, ci 0.950
std dev: 564.4432 ns, lb 176.8846 ns, ub 1.272104 us, ci 0.950
found 9 outliers among 100 samples (9.0%)
  4 (4.0%) high mild
  5 (5.0%) high severe
variance introduced by outliers: 7.509%
variance is slightly inflated by outliers

benchmarking 1000/mie_strstr()
mean: 8.236142 us, lb 8.229566 us, ub 8.243420 us, ci 0.950
std dev: 35.53558 ns, lb 30.82876 ns, ub 45.21518 ns, ci 0.950

benchmarking 5000/strstr()
mean: 42.58160 us, lb 41.47477 us, ub 43.80685 us, ci 0.950
std dev: 5.965863 us, lb 5.374374 us, ub 6.354304 us, ci 0.950
variance introduced by outliers: 88.369%
variance is severely inflated by outliers

benchmarking 5000/fast_strstr()
mean: 231.5363 us, lb 231.3348 us, ub 231.9517 us, ci 0.950
std dev: 1.422824 us, lb 847.6358 ns, ub 2.474293 us, ci 0.950

benchmarking 5000/mie_strstr()
mean: 45.52594 us, lb 45.49455 us, ub 45.55893 us, ci 0.950
std dev: 164.9779 ns, lb 143.3672 ns, ub 199.6821 ns, ci 0.950

benchmarking 10000/strstr()
mean: 96.83963 us, lb 95.99696 us, ub 97.91808 us, ci 0.950
std dev: 4.864879 us, lb 4.017151 us, ub 5.624877 us, ci 0.950
found 17 outliers among 100 samples (17.0%)
  17 (17.0%) high severe
variance introduced by outliers: 48.452%
variance is moderately inflated by outliers

benchmarking 10000/fast_strstr()
mean: 470.0260 us, lb 469.8794 us, ub 470.2191 us, ci 0.950
std dev: 856.1132 ns, lb 697.5609 ns, ub 1.161968 us, ci 0.950

benchmarking 10000/mie_strstr()
mean: 95.75350 us, lb 95.69973 us, ub 95.80993 us, ci 0.950
std dev: 282.3869 ns, lb 248.7546 ns, ub 344.0236 ns, ci 0.950

benchmarking 50000/strstr()
mean: 569.0388 us, lb 568.7658 us, ub 569.5061 us, ci 0.950
std dev: 1.781933 us, lb 1.197370 us, ub 3.233906 us, ci 0.950

benchmarking 50000/fast_strstr()
mean: 2.368961 ms, lb 2.368487 ms, ub 2.369507 ms, ci 0.950
std dev: 2.617152 us, lb 2.256877 us, ub 3.121534 us, ci 0.950

benchmarking 50000/mie_strstr()
mean: 510.7503 us, lb 510.5774 us, ub 510.9565 us, ci 0.950
std dev: 964.4506 ns, lb 822.0248 ns, ub 1.266437 us, ci 0.950

benchmarking 147277/strstr()
mean: 1.673027 ms, lb 1.672212 ms, ub 1.674162 ms, ci 0.950
std dev: 4.880307 us, lb 3.711457 us, ub 6.405417 us, ci 0.950

benchmarking 147277/fast_strstr()
mean: 6.976133 ms, lb 6.975463 ms, ub 6.977392 ms, ci 0.950
std dev: 4.541033 us, lb 2.743807 us, ub 7.847657 us, ci 0.950

benchmarking 147277/mie_strstr()
mean: 1.492003 ms, lb 1.491102 ms, ub 1.493762 ms, ci 0.950
std dev: 6.190120 us, lb 3.834420 us, ub 10.78767 us, ci 0.950

**Comment by RaphaelJ** [comment]
Really impressive performances.

However I don't think it would be a great idea to compare an hand written ASM implementation to a basic C implementation.
Nevertheless, I plan to write a SIMD implementation of my algorithm, so I keep an eye on yours so I will be able to compare both.
